name: CI/CD Pipeline for Service1 and Service2

on:
  push:
    tags:
      - 'v*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push Service1 Docker image using Debian Bookworm
      uses: docker/build-push-action@v3
      with:
        context: ./service1
        push: true
        tags: pjuwy/service1:${{ github.ref_name }} 

    - name: Build and push Service2 Docker image using Debian Bookworm
      uses: docker/build-push-action@v3
      with:
        context: ./service2
        push: true
        tags: pjuwy/service2:${{ github.ref_name }}
